// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class linkcontentcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(linkcontentcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202101110351224_link-content-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
